apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus.yaml
  - prometheus-secrets.yaml
  - prometheus-deployment.yaml
  - prometheus-pvc.yaml
  - prometheus-service.yaml
  - prometheus-sa.yaml
  - prometheus-roles.yaml
  - prometheus-scraper-rolebindings.yaml
  - prometheus-viewer-rolebinding.yaml
  - prometheus-route.yaml